### ISSUE TITLE
Reporte de Práctica

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-entrevista-sistemhuerto#1]
Aquí se anexa el reporte de práctica...

**Comment by Nayee123** [comment]
20% buen trabajo

**Comment by javiern-778** [comment]
[S3GPS 02 - Práctica SmartSheet.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-entrevista-sistemhuerto/files/9932580/S3GPS.02.-.Practica.SmartSheet.pdf)

**Comment by Nayee123** [comment]
Bueno trabajo 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
